const constants = {
    ASSET_NAMES: [
        'hand.png',
        'wood.png',
        'stone/stone-150.png',
        'iron/iron-150.png',
        'gold/gold-150.png',
        'diamond/diamond-150.png',
        'emerald/emerald-150.png',
        'amethyst/amethyst-150.png',
        'diamond/diamond-150.png',
        'woodsword.png',
        'woodpickaxe.png',
        'woodaxe.png',
        'stonesword.png',
        'stonepickaxe.png',
        'stoneaxe.png',
        'woodwall.png',
        'wooddoor.png',
        'stonewall.png',
        'stonedoor.png',
        'favicon.png',
    ],
    MSG_TYPES: {
        JOIN_GAME: 0,
        GAME_FULL: 1,
        GAME_LOADING: 2,
        GAME_STATE: 3,
        GAME_UPDATE: 4,
        GAME_OVER: 5,
        ADD_ENTITY: 6,
        REMOVE_ENTITY: 7,
        SOCKET_ID: 8,
        INPUT: 9,
        SELF_UPDATE: 10,
        CRAFT_ITEM: 11,
        EQUIP_ITEM: 12,
        DROP_ITEM: 13,
        PICKUP_ITEM: 14,
        LEADERBOARD: 15,
        DROPPED_ITEMS_ADD: 16,
        DROPPED_ITEMS_REMOVE: 17,
        ACTION_KEY: 18,
        PLAYER_ID: 19,
        PLAYER_VISUAL: 20,
    },
    PLAYER: {
        TYPE: 0,
        LIMIT: 255,
        WALL_LIMIT: 255,
    },
    TREE: {
        TYPE: 1,
        LIMIT: 30,
    },
    STONE: {
        TYPE: 2,
        LIMIT: 5,
    },
    WALL: {
        TYPE: 3,
    },
    MATERIAL: {
        WOOD: 1,
        STONE: 2,
    },
    TICK_SPEED: 10,
    MAP: {
        WIDTH: Math.pow(2, 11),
        HEIGHT: Math.pow(2, 11),
    },
};
export default constants;
